ui:
 image: paulopez/quiz-ui
 environment:
  - SERVICE_NAME=quiz-ui
  - API_HOST=quiz-api
  - API_PORT=3030

 ports:
  - 80:3000
 links:
  - api

api:
 image: paulopez/quiz-api
 environment:
  - QUIZ_API_HOST=quiz-api-db
  - QUIZ_API_PORT=5000
  - REDIS_HOST=redis
  - REDIS_PORT=6379
 ports:
  - 3030:3030
 links:
  - apidb
  - redis

worker:
 image: paulopez/quiz-worker
 environment:
  - QUIZ_API_HOST=quiz-api-db
  - QUIZ_API_PORT=5000
  - REDIS_HOST=redis
  - REDIS_PORT=6379
 links:
  - apidb
  - redis

apidb:
 image: paulopez/quiz-api-db
 ports:
  - 5000:5000

redis:
  image: redis:alpine
  ports:
  - 6379:6379
