ui:
 image: paulopez/quiz-ui
 ports:
  - 80:3000
 links:
  - api

api:
 image: paulopez/quiz-api
 ports:
  - 3030:3030
 links:
  - apidb
  - redis

worker:
 image: paulopez/quiz-worker
 links:
  - apidb
  - redis

apidb:
 image: paulopez/quiz-api-db
 ports:
  - 5000:5000

redis:
  image: redis:alpine
  ports:
  - 6379:6379
