version: "2"

services:
  interlock:
      image: ehazlett/interlock:latest
      command: -D run
      tty: true
      ports:
          - 8080
      environment:
          INTERLOCK_CONFIG: |
              ListenAddr = ":8080"
              DockerURL = "${SWARM_HOST}"
              TLSCACert = "/var/lib/boot2docker/ca.pem"
              TLSCert = "/var/lib/boot2docker/server.pem"
              TLSKey = "/var/lib/boot2docker/server-key.pem"
              [[Extensions]]
              Name = "nginx"
              ConfigPath = "/etc/nginx/nginx.conf"
              PidPath = "/etc/nginx/nginx.pid"
              MaxConn = 1024
              Port = 80
      volumes:
          - /var/lib/boot2docker:/var/lib/boot2docker:ro

  nginx:
      image: nginx:latest
      entrypoint: nginx
      command: -g "daemon off;" -c /etc/nginx/nginx.conf
      ports:
          - 80:80
      labels:
          - "interlock.ext.name=nginx"
