version: "2"

services:
  interlock:
      image: ehazlett/interlock:1.1.0
      command: run
      tty: true
      ports:
        - 8080
      environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/var/lib/boot2docker/ca.pem"
            TLSCert = "/var/lib/boot2docker/server.pem"
            TLSKey = "/var/lib/boot2docker/server-key.pem"

            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/var/run/nginx.pid"
            TemplatePath = "/etc/interlock/nginx.conf.template"
            MaxConn = 1024
            Port = 80
      volumes:
        - ./nginx.conf.template:/etc/interlock/nginx.conf.template
        - /var/lib/boot2docker:/var/lib/boot2docker:ro
      restart: always

  nginx:
      image: nginx:latest
      entrypoint: nginx
      command: -g "daemon off;" -c /etc/nginx/nginx.conf
      ports:
        - 80:80
      labels:
        interlock.ext.name: "nginx"
      restart: always
